Traceback (most recent call last):
  File "./filtredGAModel.py", line 47, in <module>
    main()
  File "./filtredGAModel.py", line 42, in main
    execEtasGaModelClustered(year, region, depth=depth, save=True)
  File "./filtredGAModel.py", line 24, in execEtasGaModelClustered
    observation=model.loadModelFromFile('../Zona3/clustered_listaGA_new_real/'+str(4.0)+region+'real'+str(depth)+"_"+str(year)+'.txt', real=True)
TypeError: loadModelFromFile() got an unexpected keyword argument 'real'
